version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 
    ports:
      - '3316:3306'
    volumes:
      - ./back/api/db/mysql/volumes:/var/lib/mysql
  rails:
    build: ./back/api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./back/api:/rails
    ports:
      - "5000:5000"
    tty: true
    depends_on:
      - db
  nuxt:
    build: ./front/toC
    command: npm run dev
    volumes:
      - ./nuxt:/nuxt
    ports:     
      - "3000:3000"
